<a href="https://colab.research.google.com/github/eman-kanwal61/consoleApp/blob/main/Voice_Emotion_ai.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Installing libraries

In [ ]:
!pip install librosa scikit-learn joblib numpy pandas

Upload dataset

In [ ]:
import os
os.environ['KAGGLE_API_TOKEN'] = 'export KAGGLE_API_TOKEN=KGAT_b5c350cb1c4a182a4e1362436c554205'

In [ ]:
import os
os.environ['KAGGLE_API_TOKEN'] = 'mkdir -p ~/.kaggle && echo KGAT_b5c350cb1c4a182a4e1362436c554205 > ~/.kaggle/access_token && chmod 600 ~/.kaggle/access_token'

In [ ]:
!pip install kaggle

In [ ]:
!mkdir -p ~/.kaggle
!echo $KAGGLE_API_TOKEN > ~/.kaggle/access_token
!chmod 600 ~/.kaggle/access_token

In [ ]:
!kaggle datasets download -d uwrfkaggler/ravdess-emotional-speech-audio

Dataset URL: https://www.kaggle.com/datasets/uwrfkaggler/ravdess-emotional-speech-audio
License(s): CC-BY-NC-SA-4.0
100% 429M/429M [00:03<00:00, 128MB/s]



In [ ]:
!unzip ravdess-emotional-speech-audio.zip -d dataset

Archive:  ravdess-emotional-speech-audio.zip
  inflating: dataset/Actor_01/03-01-01-01-01-01-01.wav  
  inflating: dataset/Actor_01/03-01-01-01-01-02-01.wav  
  inflating: dataset/Actor_01/03-01-01-01-02-01-01.wav  
  inflating: dataset/Actor_01/03-01-01-01-02-02-01.wav  
  inflating: dataset/Actor_01/03-01-02-01-01-01-01.wav  
  inflating: dataset/Actor_01/03-01-02-01-01-02-01.wav  
  inflating: dataset/Actor_01/03-01-02-01-02-01-01.wav  
  inflating: dataset/Actor_01/03-01-02-01-02-02-01.wav  
  inflating: dataset/Actor_01/03-01-02-02-01-01-01.wav  
  inflating: dataset/Actor_01/03-01-02-02-01-02-01.wav  
  inflating: dataset/Actor_01/03-01-02-02-02-01-01.wav  
  inflating: dataset/Actor_01/03-01-02-02-02-02-01.wav  
  inflating: dataset/Actor_01/03-01-03-01-01-01-01.wav  
  inflating: dataset/Actor_01/03-01-03-01-01-02-01.wav  
  inflating: dataset/Actor_01/03-01-03-01-02-01-01.wav  
  inflating: dataset/Actor_01/03-01-03-01-02-02-01.wav  
  inflating: dataset/Actor_01/03-01-03-02-0

checking the folder of dataset


In [ ]:
import os

os.listdir("dataset")[:10]

['audio_speech_actors_01-24',
 'Actor_14',
 'Actor_03',
 'Actor_01',
 'Actor_24',
 'Actor_17',
 'Actor_05',
 'Actor_13',
 'Actor_16',
 'Actor_21']

In [ ]:
os.listdir("dataset")

['audio_speech_actors_01-24',
 'Actor_14',
 'Actor_03',
 'Actor_01',
 'Actor_24',
 'Actor_17',
 'Actor_05',
 'Actor_13',
 'Actor_16',
 'Actor_21',
 'Actor_10',
 'Actor_23',
 'Actor_08',
 'Actor_04',
 'Actor_07',
 'Actor_18',
 'Actor_09',
 'Actor_02',
 'Actor_06',
 'Actor_12',
 'Actor_19',
 'Actor_22',
 'Actor_20',
 'Actor_11',
 'Actor_15']

total files

In [ ]:
import glob

files = glob.glob("dataset/**/*.wav", recursive=True)

print("Total audio files:", len(files))
print(files[:5])

Total audio files: 2880
['dataset/audio_speech_actors_01-24/Actor_14/03-01-02-02-01-01-14.wav', 'dataset/audio_speech_actors_01-24/Actor_14/03-01-05-02-01-01-14.wav', 'dataset/audio_speech_actors_01-24/Actor_14/03-01-02-02-01-02-14.wav', 'dataset/audio_speech_actors_01-24/Actor_14/03-01-07-02-01-02-14.wav', 'dataset/audio_speech_actors_01-24/Actor_14/03-01-07-02-02-01-14.wav']


checking labels

In [ ]:
emotion_map = {
    "01": "neutral",
    "03": "happy",
    "04": "sad",
    "05": "angry",
    "06": "stress"
}

for file in files[:10]:
    name = file.split("/")[-1]
    emotion_code = name.split("-")[2]

    if emotion_code in emotion_map:
        print(name, "=>", emotion_map[emotion_code])

03-01-05-02-01-01-14.wav => angry
03-01-05-02-02-01-14.wav => angry
03-01-03-01-01-01-14.wav => happy
03-01-04-02-02-01-14.wav => sad


Extracting MFFC features


In [ ]:
import librosa
import numpy as np

X = []
y = []

emotion_map = {
    "01": "neutral",
    "03": "happy",
    "04": "sad",
    "05": "angry",
    "06": "stress"
}

for file in files:
    name = file.split("/")[-1]
    emotion_code = name.split("-")[2]

    if emotion_code in emotion_map:
        signal, sr = librosa.load(file, duration=3, offset=0.5)

        mfcc = librosa.feature.mfcc(y=signal, sr=sr, n_mfcc=40)
        mfcc_mean = np.mean(mfcc.T, axis=0)

        X.append(mfcc_mean)
        y.append(emotion_map[emotion_code])

print("Features Ready:", len(X))
print("Labels Ready:", len(y))
print("One Sample Shape:", X[0].shape)

Features Ready: 1728
Labels Ready: 1728
One Sample Shape: (40,)


In [ ]:
!pip install librosa scikit-learn joblib numpy pandas

In [ ]:
import glob

files = glob.glob("dataset/**/*.wav", recursive=True)

print("Total audio files:", len(files))
print(files[:5])

Total audio files: 2880
['dataset/audio_speech_actors_01-24/Actor_14/03-01-02-02-01-01-14.wav', 'dataset/audio_speech_actors_01-24/Actor_14/03-01-05-02-01-01-14.wav', 'dataset/audio_speech_actors_01-24/Actor_14/03-01-02-02-01-02-14.wav', 'dataset/audio_speech_actors_01-24/Actor_14/03-01-07-02-01-02-14.wav', 'dataset/audio_speech_actors_01-24/Actor_14/03-01-07-02-02-01-14.wav']


train voice.py

In [ ]:
%%writefile train_voice.py

import os
import glob
import librosa
import numpy as np
import pandas as pd
import joblib

from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


# =========================
# 1. Dataset Path
# =========================

DATASET_PATH = "dataset"

files = glob.glob(DATASET_PATH + "/**/*.wav", recursive=True)

print("Total audio files found:", len(files))


# =========================
# 2. Emotion Mapping
# =========================
# RAVDESS filename example:
# 03-01-05-02-01-01-14.wav
# 3rd number = emotion code
#
# 01 = neutral
# 03 = happy
# 04 = sad
# 05 = angry
# 06 = fear, hum ise stress bana rahe hain

emotion_map = {
    "01": "neutral",
    "03": "happy",
    "04": "sad",
    "05": "angry",
    "06": "stress"
}


# =========================
# 3. MFCC Feature Function
# =========================

def extract_mfcc(file_path):
    """
    Ye function audio file leta hai aur usko MFCC features me convert karta hai.
    Output: 40 numbers ka feature vector
    """

    try:
        audio, sample_rate = librosa.load(file_path, duration=3, offset=0.5)

        mfcc = librosa.feature.mfcc(
            y=audio,
            sr=sample_rate,
            n_mfcc=40
        )

        mfcc_mean = np.mean(mfcc.T, axis=0)

        return mfcc_mean

    except Exception as e:
        print("Error processing file:", file_path)
        print("Error:", e)
        return None


# =========================
# 4. Extract Features
# =========================

X = []
y = []

for file in files:
    file_name = os.path.basename(file)

    try:
        emotion_code = file_name.split("-")[2]
    except:
        continue

    if emotion_code in emotion_map:
        features = extract_mfcc(file)

        if features is not None:
            X.append(features)
            y.append(emotion_map[emotion_code])


X = np.array(X)
y = np.array(y)

print("Features shape:", X.shape)
print("Labels shape:", y.shape)


# =========================
# 5. Check Class Distribution
# =========================

print("\nEmotion counts:")
print(pd.Series(y).value_counts())


# =========================
# 6. Train-Test Split
# =========================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("\nTraining samples:", len(X_train))
print("Testing samples:", len(X_test))


# =========================
# 7. Build SVM Model
# =========================
# StandardScaler features ko normalize karta hai
# SVC classifier emotion classify karta hai

model = Pipeline([
    ("scaler", StandardScaler()),
    ("svm", SVC(kernel="rbf", C=10, gamma="scale", probability=True))
])


# =========================
# 8. Train Model
# =========================

print("\nTraining started...")
model.fit(X_train, y_train)
print("Training completed.")


# =========================
# 9. Evaluate Model
# =========================

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)

print("\nModel Accuracy:", accuracy)

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))


# =========================
# 10. Save Model
# =========================

os.makedirs("models", exist_ok=True)

joblib.dump(model, "models/voice_model.pkl")

print("\nModel saved successfully at: models/voice_model.pkl")

Writing train_voice.py


Run the file

In [ ]:
!python train_voice.py

Total audio files found: 2880
Features shape: (1728, 40)
Labels shape: (1728,)

Emotion counts:
angry      384
happy      384
sad        384
stress     384
neutral    192
Name: count, dtype: int64

Training samples: 1382
Testing samples: 346

Training started...
Training completed.

Model Accuracy: 0.9508670520231214

Classification Report:
              precision    recall  f1-score   support

       angry       0.97      0.97      0.97        77
       happy       0.92      0.95      0.94        77
     neutral       0.95      0.95      0.95        38
         sad       0.94      0.95      0.94        77
      stress       0.97      0.94      0.95        77

    accuracy                           0.95       346
   macro avg       0.95      0.95      0.95       346
weighted avg       0.95      0.95      0.95       346


Confusion Matrix:
[[75  2  0  0  0]
 [ 2 73  0  2  0]
 [ 0  0 36  2  0]
 [ 0  2  0 73  2]
 [ 0  2  2  1 72]]

Model saved successfully at: models/voice_model.pkl


checking saved model

In [ ]:
import os

os.listdir("models")

['voice_model.pkl']

testing prediction of model


In [ ]:
import joblib
import librosa
import numpy as np
import glob
import os

model = joblib.load("models/voice_model.pkl")

def extract_mfcc(file_path):
    audio, sample_rate = librosa.load(file_path, duration=3, offset=0.5)
    mfcc = librosa.feature.mfcc(y=audio, sr=sample_rate, n_mfcc=40)
    mfcc_mean = np.mean(mfcc.T, axis=0)
    return mfcc_mean

files = glob.glob("dataset/**/*.wav", recursive=True)

test_file = files[0]

features = extract_mfcc(test_file)
features = features.reshape(1, -1)

prediction = model.predict(features)[0]

print("Test file:", os.path.basename(test_file))
print("Predicted emotion:", prediction)

Test file: 03-01-02-02-01-01-14.wav
Predicted emotion: neutral


In [ ]:
import os
os.listdir()

['.config',
 'train_voice.py',
 'models',
 '.ipynb_checkpoints',
 'dataset',
 'ravdess-emotional-speech-audio.zip',
 'sample_data']

In [ ]:
import glob
import os
import joblib
import librosa
import numpy as np

model = joblib.load("models/voice_model.pkl")

emotion_map = {
    "01": "neutral",
    "03": "happy",
    "04": "sad",
    "05": "angry",
    "06": "stress"
}

def extract_mfcc(file_path):
    audio, sample_rate = librosa.load(file_path, duration=3, offset=0.5)
    mfcc = librosa.feature.mfcc(y=audio, sr=sample_rate, n_mfcc=40)
    mfcc_mean = np.mean(mfcc.T, axis=0)
    return mfcc_mean

files = glob.glob("dataset/**/*.wav", recursive=True)

# Sirf wahi files lo jo hamari 5 emotions me hain
valid_files = []

for file in files:
    file_name = os.path.basename(file)
    emotion_code = file_name.split("-")[2]

    if emotion_code in emotion_map:
        valid_files.append(file)

print("Valid test files:", len(valid_files))

# Pehli valid file test karo
test_file = valid_files[0]

features = extract_mfcc(test_file)
features = features.reshape(1, -1)

prediction = model.predict(features)[0]

file_name = os.path.basename(test_file)
emotion_code = file_name.split("-")[2]
actual_emotion = emotion_map[emotion_code]

print("Test file:", file_name)
print("Actual emotion:", actual_emotion)
print("Predicted emotion:", prediction)

Valid test files: 1728
Test file: 03-01-05-02-01-01-14.wav
Actual emotion: angry
Predicted emotion: angry


In [ ]:
import os

os.listdir("models")

['voice_model.pkl']

RECOMMENDATION ENGINE

Stress + Student + Night → breathing before sleep
Angry + Worker + Day → take short walk
Sad + Alone → call a friend

In [ ]:
%%writefile recommendation.py

def recommend(emotion, user_type="student", time_of_day="day"):
    """
    emotion: happy, sad, angry, stress, neutral
    user_type: student, worker, general
    time_of_day: morning, day, evening, night
    """

    emotion = emotion.lower()
    user_type = user_type.lower()
    time_of_day = time_of_day.lower()

    if emotion == "stress":
        if user_type == "student" and time_of_day == "night":
            return [
                "2 minute deep breathing exercise karo.",
                "Phone side par rakh kar 10 minutes relax karo.",
                "Kal ke tasks short list me likh do taake mind clear ho."
            ]

        elif user_type == "student":
            return [
                "5 minute break lo aur pani piyo.",
                "Apna task chhote parts me divide karo.",
                "2 minute breathing exercise try karo."
            ]

        elif user_type == "worker":
            return [
                "Screen se 5 minutes break lo.",
                "Short walk karo.",
                "High priority task par focus karo, baqi baad me."
            ]

        else:
            return [
                "Slow breathing karo.",
                "Thoda pani piyo.",
                "Apne thoughts ko paper par likho."
            ]

    elif emotion == "sad":
        if time_of_day == "night":
            return [
                "Calm music suno.",
                "Kisi trusted friend ko message karo.",
                "Sleep routine follow karo."
            ]
        else:
            return [
                "Kisi friend ya family member se baat karo.",
                "Thodi sunlight ya fresh air lo.",
                "Apni feeling ko journal me likho."
            ]

    elif emotion == "angry":
        return [
            "5 minute walk karo.",
            "Reply dene se pehle 10 deep breaths lo.",
            "Situation se thoda distance lo aur calm hone ke baad baat karo."
        ]

    elif emotion == "happy":
        return [
            "Is positive energy ko productive task me use karo.",
            "Apni progress note karo.",
            "Kisi aur ke sath positive moment share karo."
        ]

    elif emotion == "neutral":
        return [
            "Stay balanced and hydrated.",
            "Aaj ka ek small goal set karo.",
            "Focus maintain rakhne ke liye short break schedule karo."
        ]

    else:
        return [
            "Apni current feeling ko observe karo.",
            "Deep breathing try karo.",
            "Agar feeling intense ho to kisi trusted person se baat karo."
        ]

Writing recommendation.py


TESTING recommendation engine

In [ ]:
from recommendation import recommend

result = recommend(
    emotion="stress",
    user_type="student",
    time_of_day="night"
)

for i, r in enumerate(result, 1):
    print(i, r)

1 2 minute deep breathing exercise karo.
2 Phone side par rakh kar 10 minutes relax karo.
3 Kal ke tasks short list me likh do taake mind clear ho.


Connecting voice recommendation with engine

In [ ]:
from recommendation import recommend

# Ye prediction tumhare model se aayi hui emotion hai
detected_emotion = prediction

user_type = "student"
time_of_day = "night"

suggestions = recommend(detected_emotion, user_type, time_of_day)

print("Detected Emotion:", detected_emotion)
print("\nRecommended Actions:")

for i, suggestion in enumerate(suggestions, 1):
    print(f"{i}. {suggestion}")

Detected Emotion: angry

Recommended Actions:
1. 5 minute walk karo.
2. Reply dene se pehle 10 deep breaths lo.
3. Situation se thoda distance lo aur calm hone ke baad baat karo.


In [ ]:
import os
os.listdir("models")


['voice_model.pkl']

In [ ]:
print("Actual emotion:", actual_emotion)
print("Predicted emotion:", prediction)

Actual emotion: angry
Predicted emotion: angry


In [ ]:
from recommendation import recommend

recommend(prediction, "student", "night")

['5 minute walk karo.',
 'Reply dene se pehle 10 deep breaths lo.',
 'Situation se thoda distance lo aur calm hone ke baad baat karo.']

voice prediction

In [ ]:
%%writefile voice_predict.py

import joblib
import librosa
import numpy as np
from recommendation import recommend

model = joblib.load("models/voice_model.pkl")

def extract_mfcc(file_path):
    audio, sample_rate = librosa.load(file_path, duration=3, offset=0.5)

    mfcc = librosa.feature.mfcc(
        y=audio,
        sr=sample_rate,
        n_mfcc=40
    )

    mfcc_mean = np.mean(mfcc.T, axis=0)

    return mfcc_mean


def predict_emotion_from_voice(file_path, user_type="student", time_of_day="day"):
    features = extract_mfcc(file_path)
    features = features.reshape(1, -1)

    emotion = model.predict(features)[0]

    suggestions = recommend(
        emotion=emotion,
        user_type=user_type,
        time_of_day=time_of_day
    )

    return emotion, suggestions

Writing voice_predict.py


In [ ]:
import glob
import os
from voice_predict import predict_emotion_from_voice

files = glob.glob("dataset/**/*.wav", recursive=True)

test_file = files[0]

emotion, suggestions = predict_emotion_from_voice(
    test_file,
    user_type="student",
    time_of_day="day"
)

print("Test file:", os.path.basename(test_file))
print("Predicted Emotion:", emotion)

print("\nRecommendations:")
for i, suggestion in enumerate(suggestions, 1):
    print(f"{i}. {suggestion}")

Test file: 03-01-02-02-01-01-14.wav
Predicted Emotion: neutral

Recommendations:
1. Stay balanced and hydrated.
2. Aaj ka ek small goal set karo.
3. Focus maintain rakhne ke liye short break schedule karo.


Audio file testing

In [ ]:
import glob
import os

files = glob.glob("dataset/**/*.wav", recursive=True)

print("Total wav files:", len(files))
print("First file:", files[0])

Total wav files: 2880
First file: dataset/audio_speech_actors_01-24/Actor_14/03-01-02-02-01-01-14.wav


In [ ]:
from voice_predict import predict_emotion_from_voice
import os

test_file = files[0]

emotion, suggestions = predict_emotion_from_voice(
    test_file,
    user_type="student",
    time_of_day="night"
)

print("Test file:", os.path.basename(test_file))
print("Predicted Emotion:", emotion)

print("\nRecommendations:")
for i, suggestion in enumerate(suggestions, 1):
    print(f"{i}. {suggestion}")

Test file: 03-01-02-02-01-01-14.wav
Predicted Emotion: neutral

Recommendations:
1. Stay balanced and hydrated.
2. Aaj ka ek small goal set karo.
3. Focus maintain rakhne ke liye short break schedule karo.


In [ ]:
import glob
import os

files = glob.glob("dataset/**/*.wav", recursive=True)

print("Total wav files:", len(files))
print("First 5 files:")
for f in files[:5]:
    print(f)

Total wav files: 2880
First 5 files:
dataset/audio_speech_actors_01-24/Actor_14/03-01-02-02-01-01-14.wav
dataset/audio_speech_actors_01-24/Actor_14/03-01-05-02-01-01-14.wav
dataset/audio_speech_actors_01-24/Actor_14/03-01-02-02-01-02-14.wav
dataset/audio_speech_actors_01-24/Actor_14/03-01-07-02-01-02-14.wav
dataset/audio_speech_actors_01-24/Actor_14/03-01-07-02-02-01-14.wav


In [ ]:
from voice_predict import predict_emotion_from_voice
import os

test_file = files[0]

emotion, suggestions = predict_emotion_from_voice(
    test_file,
    user_type="student",
    time_of_day="night"
)

print("Test file:", os.path.basename(test_file))
print("Full path:", test_file)
print("Predicted Emotion:", emotion)

print("\nRecommendations:")
for i, suggestion in enumerate(suggestions, 1):
    print(f"{i}. {suggestion}")

Test file: 03-01-02-02-01-01-14.wav
Full path: dataset/audio_speech_actors_01-24/Actor_14/03-01-02-02-01-01-14.wav
Predicted Emotion: neutral

Recommendations:
1. Stay balanced and hydrated.
2. Aaj ka ek small goal set karo.
3. Focus maintain rakhne ke liye short break schedule karo.


In [ ]:
angry_files = []

for f in files:
    name = os.path.basename(f)
    emotion_code = name.split("-")[2]

    if emotion_code == "05":
        angry_files.append(f)

print("Angry files:", len(angry_files))
print(angry_files[0])

Angry files: 384
dataset/audio_speech_actors_01-24/Actor_14/03-01-05-02-01-01-14.wav


In [ ]:
test_file = angry_files[0]

emotion, suggestions = predict_emotion_from_voice(
    test_file,
    user_type="student",
    time_of_day="day"
)

print("Test file:", os.path.basename(test_file))
print("Predicted Emotion:", emotion)

print("\nRecommendations:")
for i, suggestion in enumerate(suggestions, 1):
    print(f"{i}. {suggestion}")

Test file: 03-01-05-02-01-01-14.wav
Predicted Emotion: angry

Recommendations:
1. 5 minute walk karo.
2. Reply dene se pehle 10 deep breaths lo.
3. Situation se thoda distance lo aur calm hone ke baad baat karo.


In [ ]:
happy_files = []

for f in files:
    name = os.path.basename(f)
    emotion_code = name.split("-")[2]

    if emotion_code == "03":
        happy_files.append(f)

test_file = happy_files[0]

emotion, suggestions = predict_emotion_from_voice(
    test_file,
    user_type="student",
    time_of_day="day"
)

print("Test file:", os.path.basename(test_file))
print("Predicted Emotion:", emotion)

print("\nRecommendations:")
for i, suggestion in enumerate(suggestions, 1):
    print(f"{i}. {suggestion}")

Test file: 03-01-03-01-01-01-14.wav
Predicted Emotion: happy

Recommendations:
1. Is positive energy ko productive task me use karo.
2. Apni progress note karo.
3. Kisi aur ke sath positive moment share karo.


In [ ]:
sad_files = []

for f in files:
    name = os.path.basename(f)
    emotion_code = name.split("-")[2]

    if emotion_code == "04":
        sad_files.append(f)

test_file = sad_files[0]

emotion, suggestions = predict_emotion_from_voice(
    test_file,
    user_type="student",
    time_of_day="night"
)

print("Test file:", os.path.basename(test_file))
print("Predicted Emotion:", emotion)

print("\nRecommendations:")
for i, suggestion in enumerate(suggestions, 1):
    print(f"{i}. {suggestion}")

Test file: 03-01-04-02-02-01-14.wav
Predicted Emotion: sad

Recommendations:
1. Calm music suno.
2. Kisi trusted friend ko message karo.
3. Sleep routine follow karo.


In [ ]:
stress_files = []

for f in files:
    name = os.path.basename(f)
    emotion_code = name.split("-")[2]

    if emotion_code == "06":
        stress_files.append(f)

test_file = stress_files[0]

emotion, suggestions = predict_emotion_from_voice(
    test_file,
    user_type="student",
    time_of_day="night"
)

print("Test file:", os.path.basename(test_file))
print("Predicted Emotion:", emotion)

print("\nRecommendations:")
for i, suggestion in enumerate(suggestions, 1):
    print(f"{i}. {suggestion}")

Test file: 03-01-06-01-01-01-14.wav
Predicted Emotion: stress

Recommendations:
1. 2 minute deep breathing exercise karo.
2. Phone side par rakh kar 10 minutes relax karo.
3. Kal ke tasks short list me likh do taake mind clear ho.


In [ ]:
test_file = files[0]

In [ ]:
test_file = angry_files[0]